<?php $nombreSesion=$_SESSION['usuario_nombre']??''; $correoSesion=$_SESSION['usuario_correo']??''; ?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Contactar asesor - TecnoStore</title><link rel="stylesheet" href="assets/style.css"></head><body>
<aside><div class="brand">🛒 TecnoStore</div><div class="user">👤 <?=htmlspecialchars($nombreSesion)?><span>Cliente</span></div><nav><a href="index.php">🛍️ Catálogo</a><a class="active" href="index.php?accion=contactar">📞 Contactar asesor</a><a href="index.php?accion=carrito">🛒 Carrito</a></nav><a class="logout" href="index.php?controller=login&action=logout">🚪 Cerrar sesión</a></aside>
<main><header><div><h1>Contactar a un asesor</h1><p>Cuéntanos el motivo por el que necesitas ayuda y un asesor podrá atenderte.</p></div></header>
<?php if($mensaje_enviado): ?><div class="success-box"><div>✅</div><h2>Solicitud enviada correctamente</h2><p>Tu solicitud fue registrada. Un asesor revisará tu mensaje y se pondrá en contacto contigo.</p><a class="btn" href="index.php">Volver al catálogo</a></div><?php else: ?>
<section class="advisor-form"><div class="advisor-head"><div class="advisor-icon">🧑‍💼</div><div><h2>Formulario de atención</h2><p>Completa los datos para enviar tu consulta.</p></div></div>
<form method="post" action="index.php?accion=contactar">
<div class="two"><div><label>Nombre completo</label><input type="text" name="nombre" value="<?=htmlspecialchars($nombreSesion)?>" required></div><div><label>Correo electrónico</label><input type="email" name="correo" value="<?=htmlspecialchars($correoSesion)?>" required></div></div>
<label>¿Cuál es el motivo de tu contacto?</label><select name="motivo" required><option value="">Selecciona un motivo</option><option>Consulta sobre un producto</option><option>Ayuda para elegir un producto</option><option>Problema con una compra</option><option>Problema con el carrito</option><option>Consulta sobre el pago</option><option>Garantía o devolución</option><option>Otro motivo</option></select>
<label>Prioridad</label><select name="prioridad"><option>Normal</option><option>Alta</option><option>Urgente</option></select>
<label>Describe tu consulta</label><textarea name="detalle" placeholder="Escribe aquí el motivo por el que necesitas contactar al asesor..." required></textarea>
<div class="form-actions"><a class="btn secondary" href="index.php">Cancelar</a><button class="btn" type="submit">📨 Enviar solicitud al asesor</button></div>
</form></section><?php endif; ?></main></body></html>